version: '3.8'
services:
  server:
    build: ./server
    ports:
      - '5000:5000'
    env_file:
      - ./server/.env
    depends_on:
      - mongo
  client:
    build: ./client
    ports:
      - '3000:3000'
    env_file:
      - ./client/.env
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
